### ISSUE TITLE
vite_ruby can't work with 

### ISSUE THREAD

**Issue by 0xDing** [ElMassimo/vite_ruby#149]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x ] I have tried upgrading by running `bundle update vite_ruby`.
- [ x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖
When set `cssCodeSplit: false`,  has error:
```
Vite Ruby can't find entrypoints/style.css in public/esm-bundle/manifest.json or public/esm-bundle/manifest-assets.json.
```

This appears to be caused by https://github.com/ElMassimo/vite_ruby/blob/aba897ecc6d8ffb19f0e413d40c913ee897d90f1/vite_ruby/lib/vite_ruby/manifest.rb#L161

### Reproduction 🐞

set vite.config.js `cssCodeSplit: false`, and add `<%= vite_stylesheet_tag 'style.css' unless ViteRuby.instance.dev_server_running? %>` to rails layout

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.0.2
vite_rails: 3.0.1
rails: 7.0.0.alpha2
node: v16.13.1
npm: 8.1.2
yarn: 3.1.1
pnpm: Usage Error: This project is configured to use yarn

$ pnpm ...
ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

installed packages:
@brickdoc/monorepo@0.0.0 /Users/ding/Projects/brickdoc
├─┬ @brickdoc/brickdoc-headless-design-system@0.0.1 -> ./packages/brickdoc-headless-design-system
│ ├─┬ vite-plugin-mdx@3.5.8 invalid: "^3.5.10" from packages/brickdoc-headless-design-system, "^3.5.10" from packages/brickdoc-design-system
│ │ └── vite@2.6.13 deduped
│ ├─┬ vite-plugin-react-pages@3.1.1
│ │ └── vite@2.6.13 deduped
│ ├─┬ vite-plugin-react@4.0.1
│ │ └── vite@2.6.13 deduped
│ └── vite@2.6.13 deduped
├─┬ @brickdoc/design-system@0.4.2 -> ./packages/brickdoc-design-system
│ └── vite@2.6.13 deduped
├─┬ @brickdoc/editor@0.1.0 -> ./packages/brickdoc-editor
│ └─┬ @brickdoc/design-system@0.4.2 invalid: "workspace:packages/brickdoc-design-system" from packages/brickdoc-editor -> ./packages/brickdoc-design-system
│   └── vite@2.6.13 deduped
├─┬ vite-plugin-pwa@0.11.10
│ └── vite@2.6.13 deduped
├─┬ vite-plugin-ruby@3.0.3
│ └── vite@2.6.13 deduped
└── vite@2.6.13

```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
@0xDing Because most of the time tag helpers are used to reference entrypoints, they are prefixed by default.

You can disambiguate the reference by using `~/` to refer to the `sourceCodeDir`:

```erb
<%= vite_stylesheet_tag '~/style.css' %>
```

**Comment by ElMassimo** [comment]
Added to the [_Troubleshooting guide_](https://vite-ruby.netlify.app/guide/troubleshooting.html#can-t-reference-style-css-when-using-csscodesplit-false) so that it's easier to find in the future.
