### ISSUE TITLE
Syntax Error uncommenting a vite_rails template line

### ISSUE THREAD

**Issue by mdesantis** [ElMassimo/vite_ruby#154]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

The suggested code `import.meta.globEager('./**/*_channel.js')` raises the following syntax error:

```
Uncaught SyntaxError: unexpected token: ':'
```

I don't think Vite supports using `import.meta.globEager` without saving it in a variable, as the code above produces (with an `asd_channel.js` inside the `entrypoints` folder):

```js
{ "./asd_channel.js": __glob_0_0,}
```

which is a syntax error without a variable declaration (i.e. `const something = `) before.

Changing the code to something like `const _ = import.meta.globEager('./**/*_channel.js')` makes it work.

### Reproduction 🐞

_Please provide a link to a repo that can reproduce the problem you ran into._

I will if needed, but the error happens just uncommenting the line after installing `vite_rails`, so the repo may be useless.

<details>
<summary>Vite Ruby Info</summary>

```
bin/vite present?: true
vite_ruby: 3.0.3
vite_rails: 3.0.1
rails: 7.0.0.rc1
node: v14.17.5
npm: 8.0.0
yarn: 1.22.15
pnpm: 
ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

installed packages:
rails-7-demo-vite-2@ /home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2
├─┬ vite-plugin-ruby@3.0.4
│ └── vite@2.7.1 deduped
└── vite@2.7.1
```
</details>

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```
> DEBUG=vite-plugin-ruby:* bin/vite build
Building with Vite ⚡️
vite v2.7.1 building for production...
transforming...
✓ 2 modules transformed.
Unexpected token
file: /home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/app/frontend/entrypoints/application.js:24:42
22: //
23: // // Import all channels.
24: import.meta.globEager('./**/*_channel.js')
                                              ^
25: //
26: // Turbolinks.start()
error during build:
Error: Unexpected token
    at error (/home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error (/home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/node_modules/rollup/dist/shared/rollup.js:12354:16)
    at Module.tryParse (/home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/node_modules/rollup/dist/shared/rollup.js:12757:25)
    at Module.setSource (/home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/node_modules/rollup/dist/shared/rollup.js:12660:24)
    at ModuleLoader.addModuleSource (/home/maurizio/Sviluppo/rails-7/rails-7-demo-vite-2/node_modules/rollup/dist/shared/rollup.js:22138:20)

Build with Vite failed! ❌
```
</details>

### Screenshots 📷

![Schermata del 2021-12-12 13-52-26](https://user-images.githubusercontent.com/283320/145713102-aa1d7f77-8859-4c17-a469-62bd2b3bf92b.png)

**Comment by ElMassimo** [comment]
That is a problem only if there's no semicolon on the previous line, so it's not a matter of whether Vite supports it or not.

Thanks!
