### ISSUE TITLE
Document how to remove sprockets (optional)

### ISSUE THREAD

**Issue by rafafdz** [ElMassimo/vite_ruby#160]
Edit: Im referring here exclusively to `vite_rails` gem.

Just found out about vite.js and it seems to fill the gap thats missing in all the new paradigm shift going on with rails 7, so I want to give it a shot with a project.

From what I have seen, vite seems to fully replace and the old assets pipeline powered by sprockets, however at the moment of running `bundle exec vite install`, the setup script leaves it coexisting with sprockets. While this may be a a safe and wise default to use, I think most of us would like to completely replace sprockets by vite.js, so some king of flag for the task, maybe like `--rm-sprockets` that would do all the required changes for freeing up a project from sprockets, while obviously leaving vite as the new default asset pipeline would be nice!

Another alternative would be doing it by hand, while its more cumberstone, I think just a quick guide in the docs would do it!

**Comment by ElMassimo** [comment]
Contributions for a guide on how to remove sprockets are welcome.

Leaving sprockets on doesn't really affect how you use Vite Ruby, and there's no downside in keeping it there (just don't use it?).
