### ISSUE TITLE
Extra forward slash when publicOutputDir setting is blank

### ISSUE THREAD

**Issue by vtt** [ElMassimo/vite_ruby#161]
### Description 📖

When publicOutputDir setting is blank, the resulting URLs  have extra forward slash (//) and browser interpretes that as absolute path which is invalid.

### Reproduction 🐞

Use the following config/vite.json
```
{
  "all": {
    "assetsDir": "assets",
    "publicDir": "public",
    "publicOutputDir": "",
    "sourceCodeDir": "app/frontend",
    "watchAdditionalPaths": []
  },
  "development": {
    "autoBuild": true,
    "port": 3036
  },
  "test": {
    "autoBuild": true,
    "port": 3037
  }
}

```
I did not test setting blank values for `assetsDir` and `publicDir`; but I think that they would have the same problem

**Comment by ElMassimo** [comment]
For a while, the dev server proxy relied on `publicDir` as a "prefix" to [detect requests](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L53) for the Vite dev server.

Now that Vite has patched bugs related to HMR requests, the proxy can rely on [file existence](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L55).

I'll consider supporting `"publicDir": ""`, allowing you to have Vite as the only source for frontend assets if that's what you want.

**Comment by vtt** [comment]
I think the issue here is with `publicOutputDir`; the documentation does not mention that the value cannot be blank.  However, setting a blank value would generate invalid URLs.

**Comment by ElMassimo** [comment]
Sorry, typo, `publicDir` => `publicOutputDir`.
