### ISSUE TITLE
vite_javascript_tag inconsistent

### ISSUE THREAD

**Issue by KieranP** [ElMassimo/vite_ruby#167]
Code:

```
<%= vite_javascript_tag 'application', "clients/#{client_name}" %>
```

Expected:

```
/vite-ruby/entrypoints/application.js
/vite-ruby/entrypoints/clients/github.js
```

Actual:

```
/vite-ruby/entrypoints/application.js
/vite-ruby/clients/github.js
```

This results in a 404 for the client file

**Comment by ElMassimo** [comment]
It might be inconsistent, but it's [well documented](https://vite-ruby.netlify.app/guide/migrating-from-v2.html#nested-entrypoints-paths-must-be-explicit).

Avoid nesting entrypoints, you can organize your code in outer directories as needed.
