### ISSUE TITLE
Skipping vite build. Fails on Rails 7 with Capistrano 3

### ISSUE THREAD

**Issue by octave** [ElMassimo/vite_ruby#185]
Using:

- `vite_rails: 3.0.5`
- `rails: 7.0.1`
- `capistrano: 3.19.0`

After deploying when making changes to assets, it works fine. But when deploying without making any changes to the assets then during `rake assets:precompile`, what happens is `Skipping vite build. Watched files have not changed since the last build`. But after that the assets are not linked properly and the rails app crash: `ActionView::Template::Error (Vite Ruby can't find entrypoints/application.js in public/vite/manifest.json or public/vite/manifest-assets.json.`

**Comment by ElMassimo** [comment]
Seems like a capistrano configuration problem.

The build will only be skipped if a [temporary file](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/builder.rb#L40) from a previous build is found.

Normally, if that file persists, then the public dir along with the Vite output dir would also persist.

Make sure that the public dir is not being cleared upon deployment to avoid rebuilding unnecessarily, or force a build on every deployment (less efficient).
