### ISSUE TITLE
Assets manifest does not include some of the stylesheets when they have the same content

### ISSUE THREAD

**Issue by owen2345** [ElMassimo/vite_ruby#188]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖
Some stylesheet entrypoints are not recognized while building

### Reproduction 🐞

Given `app/frontend/entrypoints/application.sass.scss` and `app/frontend/entrypoints/sample.sass.scss` and `app/frontend/entrypoints/sample2.sass.scss`
When generating the assets before running tests (`bundle exec rspec`) via `bin/vite clobber && bin/vite build --mode=test --force`
Then the expected entrypoints are not generated (see screenshot) and thus it fails with the following when running tests
```
Failure/Error: = vite_stylesheet_tag 'sample.sass.scss' # tried with without extensions
Vite Ruby can't find entrypoints/sample.sass.scss in public/vite-test/manifest.json or public/vite-test/manifest-assets.json.
```
![image](https://user-images.githubusercontent.com/1148415/151952257-7e63940d-9d13-43d2-849f-8861d635574a.png)
<details>
<summary>Vite Ruby Info</summary>
```
bin/vite present?: true
vite_ruby: 3.0.8
vite_rails: 3.0.5
rails: 7.0.1
node: v12.22.5
```

_Run `bin/rake vite:info` and provide the output:_

```
root@0e060fd43d0d:/app# bin/rake vite:info
bin/vite present?: true
vite_ruby: 3.0.8
vite_rails: 3.0.5
rails: 7.0.1
node: v12.22.5
yarn: 1.22.17
pnpm: 
ruby: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]

installed packages:
app@ /app
├─┬ vite-plugin-ruby@3.0.8
│ └── vite@2.7.13 deduped
└── vite@2.7.13
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

Note: `sample.sass.scss` was not included in `assets-manifest`
```
Build with Vite complete: /app/public/vite
2022-02-01T10:43:58.100Z vite-plugin-ruby:config {
  base: '/vite/',
  build: {
    emptyOutDir: false,
    sourcemap: true,
    chunkSizeWarningLimit: '2048',
    assetsDir: 'assets',
    manifest: true,
    outDir: '../../public/vite',
    rollupOptions: { input: [Object], output: [Object] }
  },
  root: '/app/app/frontend',
  server: {
    host: 'localhost',
    https: false,
    port: 3036,
    strictPort: true,
    fs: { allow: [Array], strict: true }
  },
  entrypoints: {
    'entrypoints/application.js': '/app/app/frontend/entrypoints/application.js',
    'entrypoints/application.sass.scss': '/app/app/frontend/entrypoints/application.sass.scss',
    'entrypoints/login.sass.scss': '/app/app/frontend/entrypoints/login.sass.scss',
    'entrypoints/sample.sass.scss': '/app/app/frontend/entrypoints/sample.sass.scss',
    'entrypoints/sample2.sass.scss': '/app/app/frontend/entrypoints/sample2.sass.scss'
  }
}
2022-02-01T10:44:20.078Z vite-plugin-ruby:assets-manifest {
  manifest: Map {
    'entrypoints/application.sass.scss' => {
      file: 'assets/application.6802fa99.css',
      src: 'entrypoints/application.sass.scss'
    },
    'entrypoints/sample2.sass.scss' => {
      file: 'assets/sample.5423b091.css',
      src: 'entrypoints/sample2.sass.scss'
    }
  }
}

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
Try renaming the files from `.sass.scss` to `.scss`, and it should work as expected.

---

Since Vite currently [does not expose assets](https://github.com/vitejs/vite/issues/6627) to plugins, `vite-plugin-ruby` relies on the asset filenames when [matching a compiled file with the original entrypoint filename](https://github.com/ElMassimo/vite_ruby/blob/main/vite-plugin-ruby/src/manifest.ts#L43-L46).

As a result, Vite Ruby can't currently support files with double extensions.

---

__Question:__ what is the reason to use the `.sass.scss` filename suffix?

**Comment by owen2345** [comment]
@ElMassimo thanks for answering.
Looks like the problem is on vitejs side, see the following:
- Created a clean application with your suggestions
- I added 3 stylesheet entrypoints
   <img width="1254" alt="Screen Shot 2022-02-01 at 12 57 16 PM" src="https://user-images.githubusercontent.com/1148415/152014648-34b65153-0388-4266-95e7-52dfb92b3551.png">
- I compiled the assets using the one provided by the gem and another one by vitejs
   ![image](https://user-images.githubusercontent.com/1148415/152014993-490a2a7c-4fe7-40d1-b9ed-d7f9b81fccce.png)
- From the screenshot: I see that the first time `application2.css` was compiled, and in the second time only `application.css` was compiled 
- When I run this app via `bundle exec rspec`, I have the above reported error

Note: Based on my quick review of vite-ruby gem, it is calling `bin/vite build` when needed and enabled on `config/vite.json`

Btw: This is the content generated in `public/vite-test/manifest-assets.json`
```
{
  "entrypoints/application3.sass.scss": {
    "file": "assets/application.6802fa99.css",
    "src": "entrypoints/application3.sass.scss"
  },
  "images/mgn2.jpg": {
    "file": "assets/mgn2.e3b0c442.jpg",
    "src": "images/mgn2.jpg"
  }
}
```

Thanks again!

**Comment by ElMassimo** [comment]
@owen2345 The example application seems to be using `.sass.scss` as the extension for the stylesheets.

> [Try renaming the files from .sass.scss to .scss, and it should work as expected.](https://github.com/ElMassimo/vite_ruby/issues/188#issuecomment-1027040815)

> What is the reason to use the .sass.scss filename suffix?

**Comment by owen2345** [comment]
@ElMassimo the problem is the same:
![image](https://user-images.githubusercontent.com/1148415/152026411-0c4182c2-5e10-4eb6-a523-97f7c645e821.png)
![image](https://user-images.githubusercontent.com/1148415/152026451-d8888919-d38c-4f51-900f-540dcf999301.png)

If you want, I can create a repo with the issue. But basically, it is a clean rails 7 app with the latest version of vite-ruby.

**Comment by ElMassimo** [comment]
@owen2345 It's likely that you have the same content in these example files, and Rollup is only generating a single file.

Please provide a minimal reproduction where the content of each stylesheet is different.

**Comment by owen2345** [comment]
@ElMassimo You are right. I had similar content in all 3 sample stylesheet files.
So, perhaps this can be considered as a bug, or maybe having a warning message could be great.
Thank you so much @ElMassimo!!!

**Comment by ElMassimo** [comment]
It's definitely a limitation, though I don't think there are valid use cases to have the same content in different files 😄 

Still, I'd like to improve this in the future, provided that [Vite provides access to the processed assets](https://github.com/vitejs/vite/issues/6627).
