### ISSUE TITLE
document css file loading

### ISSUE THREAD

**Issue by martindemello** [ElMassimo/vite_ruby#195]
It took me a good bit of googling and trial and error to discover that if I installed `primer-css` via npm, the way to get it into my rails app was by adding

```
import '@primer/css/dist/primer.css'
```

in `app/frontend/entrypoints/application.js` (rather than e.g. in `application.css` or via a stylesheet tag in my erb file) 

An overview page on the various ways to install and include third-party css libraries into a vite/rails setup would have been very helpful.

**Comment by ElMassimo** [comment]
Given how many CSS libraries are available on npm, it would be quite a large section (and might go out of date quickly).

Perhaps it would be better to suggest a change in the [docs for `primer-css`](https://primer.style/css/getting-started/#paths), which already cover this?
