### ISSUE TITLE
Skipping build. Vite assets are already up-to-date (causes vite not to connect)

### ISSUE THREAD

**Issue by cj** [ElMassimo/vite_ruby#20]
```
bin/rake vite:info
Running via Spring preloader in process 70795
Is bin/vite present?: true
vite_ruby: 1.0.4
vite_rails: 2.0.2
rails: 6.1.3
node: v14.5.0
npm: 6.14.11
yarn: 1.22.4
ruby: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

vite-plugin-ruby:
app-template@0.0.0-semantic-release /Users/cj/Documents/apps/SnapNHD/snap
└── vite-plugin-ruby@1.0.13
```

When I receive the following:

```
RuntimeError - conflicting chdir during another chdir block:
  app/views/layouts/application.html.erb:13
  app/controllers/auth_controller.rb:10:in `block (2 levels) in <class:AuthController>'

Skipping build. Vite assets are already up-to-date ⚡️
Skipping build. Vite assets are already up-to-date ⚡️
```

It does not output the following in the console and vite's auto-refresh does not work:

```
[vite] connecting...
2DevTools failed to load SourceMap: Could not load content for http://localhost:3000/vite-dev/@fs/Users/cj/Documents/apps/SnapNHD/snap/node_modules/.vite/chunk.IXVMP6XR.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

p.s. I am also getting a 404 error randomly.

Let me know if I can provide any more information.

Cheers!

**Comment by cj** [comment]
I have also seen this error:

```
The server is configured with a public base URL of /vite-dev/ - did you mean to visit /vite-dev/application.js instead?
```

When visiting the URL from:

```
The resource at “http://localhost:3000/vite-dev/application.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
```

**Comment by cj** [comment]
I am also randomly seeing this in the rails logs:

```
ActionController::RoutingError (No route matches [GET] "/vite-dev/@fs/Users/cj/Documents/apps/SnapNHD/snap/node_modules/.vite/debounced.js"):


ActionController::RoutingError (No route matches [GET] "/vite-dev/@fs/Users/cj/Documents/apps/SnapNHD/snap/app/assets/channels/index.js"):
```

**Comment by ElMassimo** [comment]
The 404 suggests that either the `application.js` script is not an entrypoint, or the build failed. Please share the structure of your [`sourceCodeDir`](https://vite-ruby.netlify.app/config/#sourcecodedir)

**Comment by cj** [comment]
@ElMassimo here are the contents of those files https://gist.github.com/cj/e9f978c5d1c59ba0757b1ba0a5483f0d

![CleanShot 2021-03-01 at 09 10 13](https://user-images.githubusercontent.com/1819/109516589-f8da1d80-7a6d-11eb-840d-57aeba514f5d.png)

`bin/vite dev` is what I use to run the server when developing.

This is what I used as an example to make sure mine was setup correctly https://github.com/ElMassimo/vite_ruby/tree/main/examples/rails

I will try and get you a standalone repo today/tomorrow, thank you again for taking a look!

**Comment by cj** [comment]
@ElMassimo here is also a full output of the rails console logs when starting up https://gist.github.com/cj/506fe28316a4216767fd56f1537de18f

**Comment by ElMassimo** [comment]
A standalone repo would be great, thanks.

I won't have computer access until Wednesday, I'll take a look then.

Looking at the traces you added, something that seems odd is that these requests are not being forwarded to Vite by the dev server proxy, can you check that it's being included in the Rack middleware? Also, which Vite version are you using?

Sidenote: The components folder should live inside your source code dir (app/assets), or make sure to add it to [`watchAdditionalPaths`](https://vite-ruby.netlify.app/config/#watchadditionalpaths) so that changes are detected by Vite Ruby for recompilation when the dev server has not started.

**Comment by cj** [comment]
@ElMassimo so looks like I figured out a temporary fix by increasing `"devServerConnectTimeout": 30` from the default `0.1`.  It seems to randomly take 15+ seconds to compile sometimes, especially when loading async javascript imports.  I am going to have to do some more digging to figure out why.

**Comment by ElMassimo** [comment]
That adds up with requests not being redirected to the dev server, cool.

The timeout should not be related with the compilation time, but rather the timeout to check [whether the dev server is running](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby.rb#L87-L98).

Curious, are you using foreman to start the Rails and Vite dev servers? And if so, does it still requires a high timeout if you run the processes separately? What hardware are you using, or are you running on a VM or other resource-constrained environment?

**Comment by ElMassimo** [comment]
Added a [troubleshooting section](https://vite-ruby.netlify.app/guide/troubleshooting.html) describing possible causes.

Closing this for now, we can reopen it if none of the [steps](https://vite-ruby.netlify.app/guide/troubleshooting.html) help, and you provide a reproduction 😃

**Comment by boriscy** [comment]
> `bin/rake vite:clobber` and `bin/vite build`

Running these fixed my problems
