### ISSUE TITLE
Ability to disable/omit crossorigin HTML attribute on link and script tags

### ISSUE THREAD

**Issue by bellizio** [ElMassimo/vite_ruby#211]
**Is your feature request related to a problem? Please describe.**
I'm facing an issue where production resources (js + css) included from the `vite_javascript_tag` are blocked due to CORS errors - specifically because [crossorigin=anonymous is default setting here.](https://github.com/ElMassimo/vite_ruby/blob/0fe9ef39b66929e16bb2c40f802f1684a23cb30b/vite_rails/lib/vite_rails/tag_helpers.rb#L39) This is problematic when assets are on served via a cdn for example and a site is hosted from a different domain.

**Describe the solution you'd like**
Could we have a way to opt out of or disable setting `crossorigin` on the generated `<script>` and `<link>` tags?

`crossorigin="use-credentials"` does not seem to work, and `crossorigin=""` maps to anonymous.

**Describe alternatives you've considered**
The only alternative that currently comes to mind is for us as users of vite_ruby is to configure headers on the resources server to allow the cross origin request from the site domain(s).

**Additional context**
For compatibility reasons, we are using [vite_rails_legacy](https://github.com/ElMassimo/vite_ruby/tree/main/vite_rails_legacy).

**Comment by ElMassimo** [comment]
Hi Devon!

You can use `crossorigin: nil` to skip the attribute:

```ruby
vite_typescript_tag 'application', crossorigin: nil
```

renders

```html
<script src="/vite-dev/assets/application.2bcd08cf.js" type="module"></script>
<link rel="modulepreload" href="/vite-dev/assets/example_import.57b991ca.js" as="script">
<link rel="stylesheet" href="/vite-dev/assets/application.c9d9ac92.css" media="all">
```

If using `crossorigin: nil` does not work in your use case, please share a minimal repo with the same Rails version you are using and I can take a look.

Have in mind that I created `vite_rails_legacy` for migration purposes, but I'm not using it myself, and I have little interest in supporting it.

**Comment by bellizio** [comment]
That did the trick, thank you @ElMassimo! And also thanks for the note re: `vite-rails_legacy` - hopefully we will not be using it for too long.

**Comment by ElMassimo** [comment]
Just noticed that you work in Vimeo! By any chance do you know Max Jacobson?

**Comment by bellizio** [comment]
@ElMassimo indeed I do! @maxjacobson is my manager :)

**Comment by maxjacobson** [comment]
👋🏻 heh hey guys

**Comment by pranaybinju** [comment]
Hi @ElMassimo , 
I am also facing this issue and added `crossorigin:nil` to the `script`. But the browser sets `Fetch Metadata Request Headers` like `Sec-Fetch-Mode :cors` to the request and this still causes CORS errors while fetching the script. 
Note `script` is on a different domain and hosted on CloudFront CDN . Can you suggest any way we can prevent browser from adding this `Fetch Metadata Request Headers` ?

**Comment by ElMassimo** [comment]
@pranaybinju Haven't run into that situation. I'd recommend checking in StackOverflow, or opening a _Discussion_ providing more details, so that it's easier to find your post, and other people can help you 😃

**Comment by pranaybinju** [comment]
> @pranaybinju Haven't run into that situation. I'd recommend checking in StackOverflow, or opening a _Discussion_ providing more details, so that it's easier to find your post, and other people can help you 😃

Hi @ElMassimo 
I posted this query on [StackOverflow](https://stackoverflow.com/questions/74590225/sec-fetch-modecors-added-by-the-browser-to-the-request-headers-when-requestin?noredirect=1#comment131673605_74590225) and it seems that `type=module` which gets added to the script is causing the CORS issue. Is there any way to remove it or any other value to add for it to bypass this?

**Comment by ElMassimo** [comment]
No, all scripts in Vite will be `type=module`, except when [`@vitejs/plugin-legacy`](https://www.npmjs.com/package/@vitejs/plugin-legacy) is used.

Removing it would cause the [bundled code](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) to stop working.

**Comment by jeffmess** [comment]
@pranaybinju 

I also had this issue also using CloudFront CDN. Adding a Response Policy under my distribution resolved the problem. Leave the type as module as mentioned above.

![image](https://user-images.githubusercontent.com/66354/205801696-acf2dc8f-2ce7-4fc8-be19-b4f724927a4f.png)
