### ISSUE TITLE
vite-plugin-ruby should not have `latest` tag on npm

### ISSUE THREAD

**Issue by stackia** [ElMassimo/vite_ruby#228]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

<img width="577" alt="image" src="https://user-images.githubusercontent.com/5107241/178338028-faa7f000-4511-4504-b6bd-d6eed0f3ed4a.png">

vite-plugin-ruby v3.1.0-beta.0 should not be marked as `latest` on npm, which causes this version to be installed by default with `npm install vite-plugin-ruby`. It also breaks the auto-upgrade workflows like dependabot.

**Comment by ElMassimo** [comment]
Closing since `latest` is now `3.1.2`, but I'll keep it in mind for the next beta release (probably next year).
