### ISSUE TITLE
Additional entries outside of sourceCodeDir don't work

### ISSUE THREAD

**Issue by CyberAP** [ElMassimo/vite_ruby#236]
Example structure:

```
/
-- /js
-- /css
```

If you set your `sourceCodeDir` to `/js` and then add `['/css/**/*']` as `additionalEntrypoints` then you won't be able to reference them using helper tags.

Example reference: `vite_stylesheet_tag "css/example.css"`

**Comment by ElMassimo** [comment]
See the [documentation for `additionalEntrypoints`](https://vite-ruby.netlify.app/config/#additionalentrypoints).

> globs are relative to root, such as ["app/components/**/*.js"]

and

> vite_asset_path '/app/components/header.js' # leading slash is required

**Comment by CyberAP** [comment]
@ElMassimo thanks! I tried that, but I am trying to reference entries outside of `additionalEntrypoints` folder, which doesn't work even with leading slash for me.

**Comment by ElMassimo** [comment]
Did you configure `additionalEntrypoints: ['css/**/*']` and use `vite_stylesheet_tag "/css/example.css"`?

If you provide a minimal reproduction repo I can take a look.
