### ISSUE TITLE
Importing Rails UJS causes it to auto-start

### ISSUE THREAD

**Issue by JasonBarnabe** [ElMassimo/vite_ruby#246]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Rails UJS auto-starts when imported with vite. It doesn't do this with webpacker.

[Rails UJS will auto-start when window.Rails === Rails](https://github.com/rails/rails/blob/fa50226fcfe489ec32404007d4b766c4367ec9d2/actionview/app/assets/javascripts/rails-ujs/start.coffee#L74-L75). In the compiled JS, UJS sets `this.Rails`. When running with vite, `this` is `window`. With webpacker, it's some other object.

### Reproduction 🐞

In your entrypoint:

```
import Rails from '@rails/ujs'
// do something else with Rails, but don't Rails.start()...
```

Observe (by its effects, or by adding logging) that `Rails.start()` is being called. Also `window.Rails` is defined.

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.2.3
vite_rails: 3.0.10
rails: 6.1.6
node: v16.17.0
npm: 8.15.0
yarn: 1.22.5
pnpm: 
ruby: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]

installed packages:
Simplero@0.0.20 /www/Simplero
├─┬ @vitejs/plugin-basic-ssl@0.1.1
│ └── vite@3.0.9 deduped
├─┬ vite-plugin-erb@1.1.2
│ └── vite@3.0.9 deduped
├─┬ vite-plugin-ruby@3.1.2
│ └── vite@3.0.9 deduped
└── vite@3.0.9
```
</details>

**Comment by ElMassimo** [comment]
This is a known problem related to how `rails-ujs` is packaged.

See [this discussion](https://github.com/ElMassimo/vite_ruby/discussions/227#discussioncomment-3295718) for workarounds.
