### ISSUE TITLE
Dev mode inlined css styles in the end of head break order

### ISSUE THREAD

**Issue by 99monkey** [ElMassimo/vite_ruby#255]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [ ] I have tried upgrading by running `bundle update vite_ruby`.
- [ ] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

``` layouts/application.html.erb
<head>
     <%= vite_javascript_tag 'application' %>
     <%= vite_stylesheet_tag 'styles.css' %>
</head>
```
it's compiled to 

```
<script src="/vite-dev/entrypoints/application.js" crossorigin="anonymous" type="module"></script>
<link rel="stylesheet" media="all" href="/vite-dev/entrypoints/styles.css">
<style>...</style>
```
in dev mode styles from application.js are inlined in the end of <head/>  so last rule is  a winner.

in production mode it works correct.

It's better inject <style> right after <script scr=".../aplication.js"> to get same behavior in prod & dev.

PS I know, some issues may looks like antipattern, but many project has legacy architecture.

**Comment by ElMassimo** [comment]
Hi Eugene!

The behavior you are describing is related to Vite, so there's not much that Vite Ruby can do to help.

As an alternative, you can import `styles.css` from javascript (from `application.js` or any of its imported files).
