### ISSUE TITLE
autoBuild with failed build, app will use previous successful build

### ISSUE THREAD

**Issue by jrochkind** [ElMassimo/vite_ruby#267]
I love the `autoBuild` feature, it's part of what's making vite-ruby seem so attractive for me. Thank you for vite-ruby! I have noticed a problem with it that seems kind of serious to me though. 

With `autoBuild` on and active (no dev server running), if the current situation is a *failing or failed build*, **and** a *pre-existing past successful-but-now-out-of-date build* is already sitting with manifest at `manifest_path` (eg at `./public/vite-dev` when in development), the running app will silently use that previously succesful build. 

* There *will* be a message in your console/log, `Build with Vite failed! ❌`, but meanwhile the app running is using a _past_ build without complaint -- pretty easy to miss (especially in test!)

* In development, this can be very confusing -- you wonder, why aren't the changes I'm making taking effect? Why is this using JS (and/or CSS etc) that I could have sworn I changed? (Answer: Because your changes introduced something that caused the build to fail, so the app is still using the last succesful build). 

* In test, even more disastrously, you can get *passing* tests that are **false positives**, they are passing based on an _old_ version of JS or other assets, when they would fail with the current assets (because of failing build, and possibly for reasons of other changes as well). I *think* running with `autoBuild` and without dev server is kind of the [recommended/common path for test](https://vite-ruby.netlify.app/guide/development.html#tag-helpers-%F0%9F%8F%B7), so this is kind of unfortunate. (It *probably* won't effect most people's CI, although it can if CI is caching/re-using the vite build manifest_path between runs). 

I'm not sure if this is a bug or oversight or what, but I think it should probably be fixed?  

* If you **don't** have an existing succesful build (say you run `vite clean`), and you have a failing/failed build under `autoBuild` conditions, then you get a [ViteRuby::MissingEntrypointError](https://github.com/ElMassimo/vite_ruby/blob/ff45289f6cf176d5cad6152a511a792c711eef04/vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb) raised, which generally interrupts the running app, and at least with Rails ends up being displayed in your web browser -- or in test, the raised `MissingEntrypointError` causes test to fail and has exception message displayed in output.  The MissingEntrypointError message even notices the current failing build, and conveniently suggests that as a reason for the `MissingEntrypointError`, with troubleshooting suggestions. 

I think probably that is desirable, and this same behavior should occur whether or not you had a previously successful now-out-of-date build in `manifest_path`?  

## Diagnosis and Treatment

In `ViteRuby::Manifest#lookup`, we can see that the manifest tries to do a build if `autoBuild` is on, but then ignores the return value of the build call, and goes ahead and calls `find_manifest_entry` regardless -- this will find the previously built succesful build that remains sitting there on disk even if current source code is failing, and just uses that. 

https://github.com/ElMassimo/vite_ruby/blob/ff45289f6cf176d5cad6152a511a792c711eef04/vite_ruby/lib/vite_ruby/manifest.rb#L73-L84

This can possibly be fixed simply by having `#lookup` return `nil` for a failed build -- as it currently ends up doing for a failed build *without* a pre-existing on-disk successful build manifest. Then [lookup!](https://github.com/ElMassimo/vite_ruby/blob/ff45289f6cf176d5cad6152a511a792c711eef04/vite_ruby/lib/vite_ruby/manifest.rb#L69-L71) will raise the `MissingEntrypointError` consistently in both cases. 

I guess this is a bit confusing as the old past-succesful-but-out-of-date build and it's manifest is still there sitting on disk at `manifest_path` -- but I couldn't figure out a simple/reasonable way to have the old outdated-but-previously-succesful build/manifest be removed. And with this change at least it won't be used by `autoBuild` lookups. 

I will try PR'ing this change?

**Comment by ElMassimo** [comment]
Hi Jonathan!

Thanks for providing a detailed description.

The current behavior is intentional, but I'm willing to reconsider it.

- When testing, it makes sense to do a hard stop when the build fails (otherwise you are testing something else)
- In development, the same is probably desirable when users are making changes to the frontend without running Vite

I'm leaning towards doing a breaking change (instead of adding a config option to control this behavior). I'll prototype it and see how it feels.

**Comment by jrochkind** [comment]
Thanks for quick response! (and for vite-ruby!) Interesting, yeah, I'd argue for a hard-stop, especially in testing -- I think that's not the current behavior though? You currently do not get a hard stop when the build fails in test, under `autoBuild`, correct?

Is there a use case I'm not seeing where *using the previously succesful build* is desirable? In test? In dev? For my use cases, it's not desirable.  I am curious about in what use case you'd want the app using a previously succesful but now out of date build that happened to be still left in the manifest_path directory. 

If it's a backwards compat issue, a configuration option might make sense, perhaps with the default "off" configuration deprecated, to be "on" in a future maor version.  (If it was considered a bug, it might not be a backwards compat issue....)

I'm happy to try and help by writing a PR, if that's helpful. I've found my way basically around the code -- very nicely organized, thanks. I was currently stuck trying to set up the condition for a _test_ of "there was a previously succesful build, but NOW the build is failing", hadn't managed to make any headway on that.

**Comment by ElMassimo** [comment]
Released [this change](https://github.com/ElMassimo/vite_ruby/pull/268) in `vite_ruby@3.2.4`.

Thanks for your feedback!

**Comment by jrochkind** [comment]
thank you!
