### ISSUE TITLE
Support for @vitejs/plugin-legacy

### ISSUE THREAD

**Issue by smalluban** [ElMassimo/vite_ruby#27]
**Is your feature request related to a problem? Please describe.**

In my RoR project support for older browsers (not supporting ES modules) is required. There is a great plugin from the Vite contributors - [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) - to support that case.

Unfortunately, it does not work properly with `vite_rails_legacy` (I did not check the `vite_rails`). The `manifest.json` does not include additional chunks generated by the plugin, which are required to make it work properly. 

For now, I added the following code to the application layout:

```haml
%head
  = vite_client_tag
  = vite_javascript_tag 'application'
  = vite_javascript_tag 'application-legacy', type: nil, nomodule: ""
```

The `application-legacy` chunk is generated, but not the rest.

**Describe the solution you'd like**

I looked into the source code of the plugin, and it looks, that we should have also a list of chunks.

EDIT:

I bootstraped vite on node, and legacy plugin generates more sophisticated output (regardless of Safari 10 bugfix):

```html
<script nomodule src="/assets/polyfills-legacy.0809adaa.js"></script>
<script
  nomodule
  id="vite-legacy-entry"
  data-src="/assets/index-legacy.4271aeaa.js"
>
  System.import(
    document.getElementById("vite-legacy-entry").getAttribute("data-src")
  );
</script>
```

I am not sure how it can be integrated with this tool (as just output chunks will not be sufficient).

**Describe alternatives you've considered**

n/a.

**Comment by ElMassimo** [comment]
Hi Dominik! Thanks for the report.

Fortunately, it's possible to replicate the same behavior that the plugin performs in the `index.html` by adding a few tag helpers.

I'm about to release a new gem that includes these helpers.

<hr/>

In the meantime, here's the code:

```ruby
  # Public: Renders the vite-legacy-polyfill to enable code splitting in
  # browsers that do not support modules.
  def vite_legacy_polyfills_tag
    return if ViteRuby.instance.dev_server_running?

    name = vite_manifest.send(:manifest).keys.find { |file| file.include?('legacy-polyfills') } ||
           raise(ArgumentError, 'Vite legacy polyfill not found in manifest.json')
    tag.script(nomodule: true, src: vite_asset_path(name))
  end

  # Public: Renders a <script> tag for the specified Vite entrypoints when using
  # @vitejs/plugin-legacy, which injects polyfills.
  def vite_legacy_javascript_tag(name, asset_type: :javascript)
    return if ViteRuby.instance.dev_server_running?

    legacy_name = name.sub(/\.|$/, '-legacy\1')
    id = "vite-#{ legacy_name.tr(' .\'', '-') }-entry"
    legacy_tag = tag.script(nomodule: true, id: id, 'data-src': vite_asset_path(legacy_name, type: asset_type)) {
      "System.import(document.getElementById('#{ id }').getAttribute('data-src'))".html_safe
    }

    safe_join [vite_legacy_polyfills_tag, legacy_tag]
  end
```

and then use it as:

```erb
  <body>
    <%= yield %>
    <%= vite_legacy_javascript_tag 'application' %>
  </body>
</html>
```

**Comment by smalluban** [comment]
I tried your code, but there is a problem with `tag.script` function.

<img width="1027" alt="error" src="https://user-images.githubusercontent.com/1906677/110122003-5dbfab80-7dbf-11eb-8454-9ee250e69ae2.png">

**Comment by ElMassimo** [comment]
Gotcha, I was testing on Rails 5. Replace it with a `content_tag`:

```ruby
# Public: Allows to render HTML tags for scripts and styles processed by Vite.
module VitePluginLegacy::TagHelpers
  # Public: Renders a <script> tag for the specified Vite entrypoints when using
  # @vitejs/plugin-legacy, which injects polyfills.
  def vite_legacy_javascript_tag(name, asset_type: :javascript)
    return if ViteRuby.instance.dev_server_running?

    legacy_name = name.sub(/\.|$/, '-legacy\1')
    id = "vite-#{ legacy_name.tr(' .\'', '-') }-entry"
    import_tag = content_tag(:script, nomodule: false, id: id, 'data-src': vite_asset_path(legacy_name, type: asset_type)) {
      "System.import(document.getElementById('#{ id }').getAttribute('data-src'))".html_safe
    }

    safe_join [vite_legacy_polyfill_tag, import_tag]
  end

  # Internal: Renders the vite-legacy-polyfill to enable code splitting in
  # browsers that do not support modules.
  def vite_legacy_polyfill_tag
    return if ViteRuby.instance.dev_server_running?

    name = vite_manifest.send(:manifest).keys.find { |file| file.include?('legacy-polyfills') } ||
           raise(ArgumentError, 'Vite legacy polyfill not found in manifest.json')
    content_tag(:script, nil, nomodule: false, src: vite_asset_path(name))
  end
end
```

**Comment by smalluban** [comment]
I think `nomodule` should be set to empty string. For now, it produces `nomodule="false"`, which is not correct in sense of boolean attributes. Empty string will produce `<script nomodule>`, which is correct.

**Comment by ElMassimo** [comment]
Sorry, testing leftovers, thanks for the heads up!

Please install `gem 'vite_plugin_legacy', '0.5.1'`.

**Comment by smalluban** [comment]
We don't support Safari 10, so I agree, that it is not necessary. Thanks a lot for such a fast response with a solution! Great project btw!

**Comment by smalluban** [comment]
Tested, and I think this line should be `vite_rails_legacy`? Or one of those? I have an error when starting rails server:

> `require': cannot load such file -- vite_rails (LoadError)

https://github.com/ElMassimo/vite_ruby/blob/ae7774dc3c6bfe2c25c258870157a178eb8cbdff/vite_plugin_legacy/lib/vite_plugin_legacy/engine.rb#L3

**Comment by ElMassimo** [comment]
Sorry again! Made it a conditional require, and released as `0.5.2`.

**Comment by smalluban** [comment]
Hi again! I think we have last leftover. I am testing TypeScript in the project and `vite_legacy_javascript_tag` does not work with entrypoints written in `.ts`. It looks, that manifest now has `entrypoint.ts` instead of `entrypoint.js`. As the result, rails throws an error:

```
Vite Ruby can't find broadcast-legacy.js in /Users/dominik/Workspace/Viewcy/public/vite-dev/manifest.json or /Users/dominik/Workspace/Viewcy/public/vite-dev/manifest-assets.json.
```

**Comment by ElMassimo** [comment]
Didn't add a `vite_legacy_typescript_tag`, but you should be able to achieve the same by passing [`asset_type: :typescript`](https://github.com/ElMassimo/vite_ruby/blob/main/vite_rails/lib/vite_rails/tag_helpers.rb#L37).

It might be useful to add that helper in a future release. Please try it out and let me know how it goes.

**Comment by smalluban** [comment]
Thanks, it worked :)

**Comment by ElMassimo** [comment]
Added `vite_legacy_typescript_tag` to `vite_plugin_legacy@0.5.4`.
