### ISSUE TITLE
Vite preview mode

### ISSUE THREAD

**Issue by kikyous** [ElMassimo/vite_ruby#276]
vite has a preview command allow locally preview production build, steps:
* vite build
* vite preview

now you can start you application in preview mode (using production built files)

since vite use esbuild in dev mode, and rollup in production mode, preview mode is useful to debug production only issues.

It is awesome if vite_ruby can support preview mode.

**Comment by ElMassimo** [comment]
You can already leverage [auto-build](https://vite-ruby.netlify.app/guide/development.html#auto-build-%F0%9F%A4%96), which is enabled by default in development. When not starting the Vite dev server, a build will be triggered, and the app will use the built assets (which is what preview mode does).

If you want to test something production specific, you can always run `bin/vite build --mode production` and start your Ruby app in production mode.

**Comment by Splines** [comment]
@ryansch Thanks a lot. @ElMassimo I don't find the env variable `VITE_RUBY_MODE` on the [Configuring Vite Ruby](https://vite-ruby.netlify.app/config/) page, neither anywhere else in the docs. I'm happy to create a PR for this, just want to make sure it's really missing. In such a PR, I would:

- Explain on the [Configuring Vite Ruby](https://vite-ruby.netlify.app/config/) page what `VITE_RUBY_MODE` does.
- Add a new top-level section to the [Troubleshooting](https://vite-ruby.netlify.app/guide/troubleshooting.html) page with a heading like _Problems in Production_. From there, also link to the `VITE_RUBY_MODE` env variable.
