### ISSUE TITLE
not seeing the Vite (bolt) Ruby console message

### ISSUE THREAD

**Issue by wdiechmann** [ElMassimo/vite_ruby#288]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Doing a clean install and following the 'getting started' in the Vite documentation should leave me with a console message 

### Reproduction 🐞

```
rails new vite
cd vite
bundle add vite_rails
bundle exec vite install
vi package.json ( getting rid of license missing error)
rm package-lock.json
yarn
bin/vite dev
```

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.2.7
vite_rails: 3.0.12
rails: 7.0.4
node: v18.2.0
npm: 8.9.0
yarn: 1.22.19
pnpm: 
ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

installed packages:
vite@ /Users/walther/Deling/Walther/src/testing/vite
├─┬ vite-plugin-ruby@3.1.2
│ └── vite@3.1.8 deduped
└── vite@3.1.8
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

Hitting localhost:3000 does show the expected Rails default page -- while running `rails s` and `bin/vite dev` in two consoles, but the console.log message is nowhere to be seen -- all I get is provided in the attached screenshot from the devtools window

```
Building with Vite ⚡️
vite v3.1.8 building for production...
transforming...
✓ 1 modules transformed.
rendering chunks...
../../public/vite/manifest-assets.json             0.00 KiB
../../public/vite/manifest.json                    0.14 KiB
../../public/vite/assets/application.ff486227.js   0.13 KiB / gzip: 0.13 KiB
../../public/vite/assets/application.ff486227.js.map 1.09 KiB
Build with Vite complete: /Users/walther/Deling/Walther/src/testing/vite/public/vite
2022-10-21T09:21:47.739Z vite-plugin-ruby:config {
  base: '/vite/',
  build: {
    emptyOutDir: false,
    sourcemap: true,
    assetsDir: 'assets',
    manifest: true,
    outDir: '../../public/vite',
    rollupOptions: { input: [Object], output: [Object] }
  },
  envDir: '/Users/walther/Deling/Walther/src/testing/vite',
  root: '/Users/walther/Deling/Walther/src/testing/vite/app/javascript',
  server: {
    fs: { allow: [Array], strict: true },
    host: 'localhost',
    https: false,
    port: 3036,
    strictPort: true,
    hmr: { clientPort: 3036 }
  },
  entrypoints: {
    'entrypoints/application.js': '/Users/walther/Deling/Walther/src/testing/vite/app/javascript/entrypoints/application.js'
  }
}
2022-10-21T09:21:47.797Z vite-plugin-ruby:assets-manifest { manifest: Map(0) {} }

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

![Skærmbillede 2022-10-21 kl  11 26 38](https://user-images.githubusercontent.com/193245/197162798-2bc8b2e2-e155-4238-b7ef-e975dfa883c4.png)

**Comment by ElMassimo** [comment]
Please follow the steps in the [__Setup__](https://vite-ruby.netlify.app/guide/#setup-%F0%9F%93%A6) section.

In particular, verify that [tag helpers](https://vite-ruby.netlify.app/guide/development.html#tag-helpers-%F0%9F%8F%B7) are being injected in the layout for the view that you are rendering.

Moving to _Discussions_, but feel free to ask additional questions, or provide a link to a repo with the problem.
