### ISSUE TITLE
vite_rails: lock down vite_ruby dependency using bounded requirements (Eg ~>)

### ISSUE THREAD

**Issue by luislavena** [ElMassimo/vite_ruby#29]
### Description 📖

First, thank you for creating vite_ruby and vite_rails! 😸 

Right now `vite_rails` gem has an open ended dependency on `vite_ruby` (`>= 0`):

https://github.com/ElMassimo/vite_ruby/blob/main/vite_rails/vite_rails.gemspec#L23

This could introduce issues for installations in the future when a new version of `vite_ruby` is released that is incompatible with vite_rails 2, for example.

Ideally, these dependencies (including railties) should avoid have open-ended definitions (see Logs)

### Logs 📜

<details>
<summary>Output</summary>

When building the gem:

```
$ cd vite_ruby/vite_rails

$ gem build vite_rails.gemspec
WARNING:  open-ended dependency on railties (>= 5.1) is not recommended
  if railties is semantically versioned, use:
    add_runtime_dependency 'railties', '~> 5.1'
WARNING:  open-ended dependency on vite_ruby (>= 0) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on bundler (>= 1.3.0, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 1.3', '>= 1.3.0'
WARNING:  open-ended dependency on rubocop (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on rubocop-minitest (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on rubocop-performance (>= 0, development) is not recommended
  use a bounded requirement, such as '~> x.y'
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: vite_rails
  Version: 2.0.2
  File: vite_rails-2.0.2.gem
```
</details>

Let me know if this is OK with you and I can send over a PR.

Once again, thank you for releasing these gems! ❤️ ❤️ ❤️ 

Cheers.

**Comment by ElMassimo** [comment]
Hola Luis!

That's a great suggestion, I implemented it in #30, would appreciate a review if you have time 😃 

Planning to cut a release of all these gems (with bounded requirements) after merging it.

**Comment by luislavena** [comment]
Hola @ElMassimo!!!, that was a fast response! ⚡ 😉  

I just went over the diffs and looks awesome! Also moving the dev dependencies outside of the Gemfile and into the gemspec will make more easy for you to maintain (_insert here cheff kiss emoji_) 😊 

Once again, thank you for the promptly response and creating ViteRuby/ViteRails!!! ❤️ ❤️ ❤️ 

Cheers!

TIL: I wasn't aware you could use multiple `gemspec` instructions in Gemfile (instead of `gem :path` option). 🤯

**Comment by ElMassimo** [comment]
Means a lot coming from you, thank you Luis!

Working on https://github.com/ElMassimo/vite_ruby/pull/31, after I test it I will cut a release for all gems.

**Comment by ElMassimo** [comment]
@luislavena Released all gems with bounded requirements, thanks!

Highly recommend updating `vite_ruby`, there's some good stuff in #31.

**Comment by luislavena** [comment]
Looks awesome! Will do! (in the middle of updating an old application and moving away from sprockets) 😁 

Thank you for your work! ❤️ ❤️ ❤️ 

Have a nice weekend! 😊
