### ISSUE TITLE
Automated builds in the test environment make E2E testing very heavy

### ISSUE THREAD

**Issue by cc-kawakami** [ElMassimo/vite_ruby#291]
**Is your feature request related to a problem? Please describe.**
I occasionally use Capybara to write E2E tests and was concerned that the tests were very slow. As a result, it took me a little while to realize that it was due to the fact that vite_rails is configured to `autoBuild` in the test environment. 

**Describe the solution you'd like**
Shouldn't the default config file turn off `autoBuild` in the test environment, since the source should not be changed during testing?

https://github.com/ElMassimo/vite_ruby/blob/4dc12f6749700134dd9c6afeb1e013d853853e19/vite_rails/templates/config/rails-vite.json#L11-L15

**Comment by ElMassimo** [comment]
Hi Moeki!

You can run `assets:precompile` or `vite:build` in the CI once before running integration tests, as it will make it clearer how much time is being spent in assets vs tests.

However, `autoBuild: true` is still a good default for the test environment, as it allows users to avoid building assets manually when running tests locally, and in small apps provides a simpler CI setup.

**Comment by cc-kawakami** [comment]
I understand. Thank you.
