### ISSUE TITLE
Specifying attributes for each tag when using `vite_javascript_tag`

### ISSUE THREAD

**Issue by cc-kawakami** [ElMassimo/vite_ruby#302]
**Is your feature request related to a problem? Please describe.**
When using `vite_javascript_tag`, are there any situations where you can specify attributes for each tag? For example, for asynchronous loading of stylesheets, I would like to realize something like `<link media="print" onload="this.media='all'">`.

**Describe the solution you'd like**
What do you think about this feature? Or do you have any good ideas?

**Comment by ElMassimo** [comment]
Hi Moeki!

If you need more control around styles, I'd suggest using the `resolve_entries` APIs manually, or moving some of the styles to entrypoints and use `vite_stylesheet_tag` instead (where you can specify attributes individually).

For the purpose of asynchronously loading stylesheets, you could try using dynamic imports, as Vite has a helper that will inject the styles only once the script is imported.

For example:

```ts
import('~/styles')
```

```ts
// app/frontend/styles/index.ts
import '~/styles/global.css'
```

This would change the way that CSS is loaded, it will be injected when the dynamic import is executed (you have full control).

Have in mind that asynchronously loading CSS can cause FOUC and [Layout Shifts](https://web.dev/cls/), which can negatively affect the user experience, but this technique should be useful if you are loading CSS that is not used "above the fold".
