### ISSUE TITLE
Doesnt respect NODE_PATH

### ISSUE THREAD

**Issue by stacyharper** [ElMassimo/vite_ruby#306]

**Comment by ElMassimo** [comment]
Hi there!

Please provide more information when opening issues, otherwise it's hard to understand what the problem is and explore potential solutions 😃

**Comment by stacyharper** [comment]
Ya sorry I added some explanation ! I didnt had much time when my co-worker and me figured out the root cause of their issue.

**Comment by ElMassimo** [comment]
Thanks!

Vite Ruby relies on [npm bin](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/runner.rb#L48) to obtain the path.

[`viteBinPath`](https://vite-ruby.netlify.app/config/index.html#vitebinpath) is provided as a workaround for setups where `npm bin` doesn't resolve to the `vite` package binary. You may configure it using [`config/vite.rb`](https://vite-ruby.netlify.app/config/#ruby-configuration-file-%F0%9F%92%8E) or by setting the `VITE_RUBY_VITE_BIN_PATH` env variable, as you mentioned.

---

From the [Node.js docs](https://nodejs.org/api/modules.html#loading-from-the-global-folders):

> If the NODE_PATH environment variable is set to a colon-delimited list of absolute paths, then Node.js will search those paths for modules if they are not found elsewhere.

> On Windows, NODE_PATH is delimited by semicolons (;) instead of colons.

Attempting to support `NODE_PATH` correctly, would require duplicating node's implementation, which needs to split `NODE_PATH` using `:` or `;` depending on the OS.

> NODE_PATH is still supported, but is less necessary now that the Node.js ecosystem has settled on a convention for locating dependent modules. Sometimes deployments that rely on NODE_PATH show surprising behavior when people are unaware that NODE_PATH must be set. Sometimes a module's dependencies change, causing a different version (or even a different module) to be loaded as the NODE_PATH is searched.

I don't have plans to support `NODE_PATH`, I feel the additional complexity it would add to this library doesn't justify the benefit, as there it's not a common problem, and [`viteBinPath`](https://vite-ruby.netlify.app/config/index.html#vitebinpath) provides a simple workaround.

**Comment by stacyharper** [comment]
I'm perfectly fine with this conclusion. Let's leave the issues as
closed. This answer will lead the way to folks who struggle on the same
problem.
