### ISSUE TITLE
Warning when running under ruby 3.2.0

### ISSUE THREAD

**Issue by ragingdave** [ElMassimo/vite_ruby#338]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

When using vite_rails in conjunction with ruby 3.2.0, there is a warning popping up when running basically any rails command.
It seems to work just fine though.

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.2.14
vite_rails: 3.0.13
rails: 6.1.6.1
node: v18.14.0
npm: 9.3.1
yarn: 1.22.19
pnpm:
ruby: ruby 3.2.0 (2022-12-25 revision a528908271) +YJIT [arm64-darwin22]
```
</details>

### Logs 📜

```
vite_ruby-3.2.14/lib/vite_ruby/config.rb:144: warning: undefining the allocator of T_DATA class Oj::CStack
```

**Comment by ElMassimo** [comment]
Hi David!

Vite Ruby [uses](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/config.rb#L144) the standard library `JSON.parse` command.

Based on the warning message and the info you provided, it's likely that it's related to the `oj` version you are using:

- https://github.com/ohler55/oj/pull/737

Upgrading the version of `oj` to `v3.13.12` or higher should fix the issue.
