### ISSUE TITLE
exit code is 0 on error

### ISSUE THREAD

**Issue by username-is-already-taken2** [ElMassimo/vite_ruby#367]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Some of my assets aren't compiling (due to my code :) but after the error the exit code was still 0 so my docker build still carried on.

Just to confirm without my typo normally my assets compile fine what I'm trying to cover off with this issue is catching the error next time,

### Reproduction 🐞

ran `bundle exec rails vite:build`

![image](https://github.com/ElMassimo/vite_ruby/assets/13700297/b4df2824-c6b4-41cf-9fe7-1f127720a73b)

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

![image](https://github.com/ElMassimo/vite_ruby/assets/13700297/b68e8f69-4ecb-4280-b9fb-c22dcbff569f)
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

![image](https://github.com/ElMassimo/vite_ruby/assets/13700297/67aa9236-d006-40fc-a60b-2f05a45956b1)

</details>

**Comment by ElMassimo** [comment]
Hi Gary!

Looking at the logs, it seems that the Vite build succeeded, so it's likely that this particular error was swallowed.

Please file a minimal reproduction in Vite, or provide a reproduction if the error is specific to Vite Ruby.
