### ISSUE TITLE
CONTRIBUTING guide: running `pnpm install` rewrites lock file

### ISSUE THREAD

**Issue by mattbrictson** [ElMassimo/vite_ruby#378]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

I was following the CONTRIBUTION.md guide and ran `pnpm install` as instructed. This resulted in the `pnpm-lock.yaml` file getting completely rewritten into v6 format.

```
$ git diff --stat
pnpm-lock.yaml | 2215 ++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 1140 insertions(+), 1075 deletions(-)
```

I was confused about what to do about these local changes. After reading more about pnpm, I think the solution is:

- Update CONTRIBUTION.md to specify that pnpm 7.x is required (i.e. avoid using 8.x); or
- Update `pnpm-lock.yaml` to the new lock file format and change CI to use pnpm 8.x

### Reproduction 🐞

Steps to reproduce:

```
$ gh repo clone ElMassimo/vite_ruby
$ cd vite_ruby
$ npm i -g pnpm
$ pnpm install
```

Environment:

```
$ node -v
v18.16.1
```

```
$ pnpm -v
8.6.5
```

**Comment by ElMassimo** [comment]
Thanks Matt!
