### ISSUE TITLE
Update rack-proxy to at least 0.7.5

### ISSUE THREAD

**Issue by wollistik** [ElMassimo/vite_ruby#414]
**Is your feature request related to a problem? Please describe.**
When upgrading to Rails 7.1 we encounter some deprecation warnings from the rack-proxy gem, which is only pulled in via vite_ruby:
```
 /home/wwedelich/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:27: warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers
```

The root cause is the upgrade of rack to version 3+. This is fixed in the rack-proxy in version [0.7.5](https://github.com/ncr/rack-proxy/pull/110). Unfortunately bundler will not allow to upgrade this dependency due to the version constraint in vite_ruby.

**Describe the solution you'd like**
Please update/loosen the version constraint of rack-proxy to allow to upgrade to at least version 0.7.5 to get rid of the deprecation warnings and be ready for rack 3.1 applications.

**Comment by vladimirtemnikov** [comment]
Hello, @wollistik 

`~> 0.6, >= 0.6.1` does not lock you on 0.6, you can freely upgrade to 0.7.7

**Comment by wollistik** [comment]
Oh man, I am very sorry 😔

It was a different gem holding back the update...
