### ISSUE TITLE
Can't find SVG file in manifest after upgrade to 3.5.0

### ISSUE THREAD

**Issue by JasonBarnabe** [ElMassimo/vite_ruby#429]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

After upgrading vite_ruby from 3.3.4 to 3.5.0, I'm getting an error while rendering pages: `ActionView::Template::Error:"Vite Ruby can't find site/pages/cart/images/browser-redirect.svg in the manifests.`. The generated flies at `public/packs/vite/.vite/manifest.json` and `public/packs/vite/.vite/manifest-assets.json` do not contain a reference to this file.

It should be included because:

- `vite.json` includes `app/components/**/*_controller.js` under `additionalEntrypoints`.
- `app/components/payment_processor/stripe_fields_component_controller.js` consists of `import '~/site/pages/cart/images/browser-redirect.svg'`
- `browser-redirect.svg` is at `app/javascript/site/pages/cart/images/browser-redirect.svg`

On build, I see the message: `Generated an empty chunk: "app/components/payment_processor/stripe_fields_component_controller.js".`, however if I adjust the file to contain some actual JS and rebuild, I still get the error about the missing SVG.

This all worked on 3.3.4.

### Reproduction 🐞

Repo is private, but I can provide some snippets or run debug commands if it's helpful.

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.5.0
vite_rails: 3.0.17
rails: 7.0.8
node: v20.11.0
npm: 10.2.4
yarn: 1.22.5
pnpm: 7.14.2
ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

installed packages:
Simplero@0.0.20 /www/Simplero
├─┬ @vitejs/plugin-react@4.2.1
│ └── vite@5.0.11 deduped
├─┬ vite-plugin-mkcert@1.13.3
│ └── vite@5.0.11 deduped
├─┬ vite-plugin-relay@2.0.0
│ └── vite@5.0.11 deduped
├─┬ vite-plugin-ruby@5.0.0
│ └── vite@5.0.11 deduped
└── vite@5.0.11
```
</details>

**Comment by JuanVqz** [comment]
hey @JasonBarnabe did you solve it? 

it seems related to this https://github.com/vitejs/vite/issues/15010

[More info](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated)

If you are using `vite.config.ts` update it to `vite.config.mts`

**Comment by JasonBarnabe** [comment]
Thanks for the suggestion, but that did not solve the issue.

We ended up adding the path to `additionalEntrypoints` in vite.json and removing the import. Still not sure why this changed in 3.5.0.
