### ISSUE TITLE
SSR in production

### ISSUE THREAD

**Issue by benbonnet** [ElMassimo/vite_ruby#482]
More or less to report, i was trying out the recent evil martians intertiajs post and trying to get further with the vite ssr capabilities.
As of now, unsure if the example repo is enough to get things running, hopefully seeking here some further guidance.

Bug encountered below.

---

- [yes] I have tried upgrading by running `bundle update vite_ruby`.
- [yes] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Taking the vite ssr example (https://github.com/ElMassimo/inertia-rails-ssr-template), trying to run in "production" mode.
- build : `RAILS_ENV=production bundle exec rails assets:precompile` works ok
- run : `PORT=3000 RAILS_ENV=production overmind start` fails

### Logs 📜

```
web    | file:///xxxxx/inertia-rails-ssr-template/public/vite-ssr/ssr.js:5
web    | const pages = import.meta.globEagerDefault("../pages/*.jsx");
web    |                           ^
web    | 
web    | TypeError: (intermediate value).globEagerDefault is not a function
```

**Comment by ElMassimo** [comment]
Hi Ben!

`globEagerDefault` was an internal API in Vite which was removed in favour of passing options to `glob`:

```ts
import.meta.glob('../pages/*.jsx', { import: 'default', eager: true }),
```

Please use _Discussions_ instead of _Issues_ if you have additional questions.
