### ISSUE TITLE
Production build contains sourcemaps when they are turned off

### ISSUE THREAD

**Issue by smalluban** [ElMassimo/vite_ruby#49]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

`bundle exec vite build` generates source maps, where vite as default has them turned off. Even setting [`build.sourcmap` ](https://vitejs.dev/config/#build-sourcemap) to `false` explicitly does not work. As the result, source maps are pushed to the production environment.

**Comment by ElMassimo** [comment]
Hi Dominik. Thanks for the report!

I want the default to be consistent with what [Rails does](https://github.com/rails/webpacker/issues/769#issuecomment-458216151), but not being able to disable them explicitly is a bug.

I'll make a fix to ensure that passing `sourcemap: false` works as expected.

**Comment by smalluban** [comment]
I read the linked thread comment, and as I understand the way they go, I think your project should follow defaults from the vite project, as it is just a wrapper on top of the Vite. Within the fix you mentioned, it still will be weird, that feature that should be turned off by default, is not.

Also, in your documentation, you can read: 
> You can customize this file as needed, check Vite's plugins and config reference for more info.

The only way you can understand that sentence is that whatever vite has in the config, it will work as the vite works.

**Comment by ElMassimo** [comment]
Released `vite-plugin-ruby@1.0.18`, which allows disabling source maps in production by using `sourcemap: false`.

The default remains unchanged, as the advantages of generating source maps outweigh the disadvantages in most scenarios, and it has better alignment with the Rails ecosystem.

**Comment by smalluban** [comment]
Thanks!
