### ISSUE TITLE
Clean command is not passed second argument

### ISSUE THREAD

**Issue by brendo** [ElMassimo/vite_ruby#490]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

The `vite:clean` command builds off the default `assets:clean` task but it adds a second argument, `age_in_seconds`. This argument is ignored (as in, can't be changed, will always be 3600), when using `rake assets:clean` because the base task only accepts a single argument, `keep`:

### Reproduction 🐞

```
$ rails assets:clean[0,0]
[70, 79] in ~/.gem/ruby/3.3.4/bundler/gems/vite_ruby-92aff2135668/vite_ruby/lib/tasks/vite.rake
    70|   unless Rake::Task.task_defined?('assets:clean')
    71|     desc 'Remove old compiled assets'
    72|     Rake::Task.define_task('assets:clean', [:keep, :age])
    73|   end
    74|   Rake::Task['assets:clean'].enhance do |_, args|
=>  75|     debugger
    76|     Rake::Task['vite:clean'].invoke(*args.to_h.values)
    77|   end
    78| 
    79|   if Rake::Task.task_defined?('assets:clobber')
=>#0	block {|_=<Rake::Task assets:clean => [environment]..., args=#<Rake::TaskArguments keep: 0>|} in <main> at ~/.gem/ruby/3.3.4/bundler/gems/vite_ruby-92aff2135668/vite_ruby/lib/tasks/vite.rake:75
  #1	block {|act=#<Proc:0x00000001204abd90 /Users/brendana...|} in execute at ~/.gem/ruby/3.3.4/gems/rake-13.2.1/lib/rake/task.rb:279
  # and 29 frames (use `bt' command for all frames)
(rdbg) args
#<Rake::TaskArguments keep: 0>
(ruby) args.to_h
{:keep=>"0"}
(rdbg) exit
```

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.5.0
vite_rails: 3.0.17
rails: 7.1.3.4
node: v20.15.1
npm: 10.7.0
yarn: 1.22.22
pnpm: 9.4.0
ruby: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
```
</details>

To mitigate, one has to run the vite clean command directly, eg. `rake vite:clean[0,0]`

**Comment by ElMassimo** [comment]
Closed in [824b4ef](https://github.com/ElMassimo/vite_ruby/commit/824b4ef8397828423d2ddda117bf27e365954961).
