### ISSUE TITLE
A preload for 'http://localhost:4000/vite-dev/application.js' is found, but is not used because the script type does not match.

### ISSUE THREAD

**Issue by nyrf** [ElMassimo/vite_ruby#52]
### Description 📖

Visit page, chrome show warnings and i found `application.js` requsted twice.

### Reproduction 🐞

Created by https://github.com/ElMassimo/jumpstart-vite

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 1.2.2
vite_rails: 2.0.8
rails: 6.1.3.1
node: v15.4.0
npm: 7.0.15
yarn: 1.22.5
pnpm:
ruby: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin18]
```
</details>

### Screenshots 📷

<img width="1252" alt="WX20210415-150221@2x" src="https://user-images.githubusercontent.com/299532/114827776-affede00-9dfb-11eb-8be5-f405c92eabd7.png">

<img width="830" alt="WX20210415-150106@2x" src="https://user-images.githubusercontent.com/299532/114827715-9e1d3b00-9dfb-11eb-8e8c-6c6874ed9536.png">

**Comment by ElMassimo** [comment]
Hi there, thanks for the report.

This is a [__bug in Rails early preload hints__](https://github.com/ElMassimo/vite_ruby/discussions/45).

See [this discussion](https://github.com/ElMassimo/vite_ruby/discussions/45) for possible fixes.

**Comment by nyrf** [comment]
Thanks,
