### ISSUE TITLE
Problem with vite_picture_tag tag

### ISSUE THREAD

**Issue by AxelBriche** [ElMassimo/vite_ruby#520]
I use:
`<%= vite_picture_tag 'images/clock.webp', class: "w-32 h-32 inline-block", alt: "Horloge" %>`

Output:
```
<picture class="w-32 h-32 inline-block" alt="Horloge">
    <img src="/vite-dev/images/clock.webp">
</picture>
```

The "alt" is not on the img tag.
Expected output:

```
<picture class="w-32 h-32 inline-block">
  <source srcset="/vite-dev/images/clock.webp" type="image/webp">
  <img src="/vite-dev/images/clock.jpg" alt="Horloge">
</picture>
```

**Comment by ElMassimo** [comment]
Hi Axel!

We are [forwarding all options](https://github.com/ElMassimo/vite_ruby/blob/main/vite_rails/lib/vite_rails/tag_helpers.rb#L92) to `picture_tag`.

It looks like [your usage is not correct](https://github.com/rails/rails/blob/main/actionview/lib/action_view/helpers/asset_tag_helper.rb#L488), you should pass an `image: {alt: "Horloge"}` option.

**Comment by AxelBriche** [comment]
Ok thank you, the do don't say anything about it:
https://vite-ruby.netlify.app/guide/rails.html#tag-helpers-%F0%9F%8F%B7

**Comment by ElMassimo** [comment]
The docs have an example with the correct usage:

<img width="801" alt="Screenshot 2024-12-05 at 14 06 37" src="https://github.com/user-attachments/assets/2e85a246-4a5b-4330-933f-a743ac1c4ad3">

It's ok to miss it it the first time, though.
