### ISSUE TITLE
vite_rails: No support for new manifest path in Vite 5

### ISSUE THREAD

**Issue by skukx** [ElMassimo/vite_ruby#523]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

npm:
* vite: '5.4.11'

ruby:
* vite_rails: '3.0.19'

Vite 5 has changed the location of the generated `manifest.json` and `manifest.assets.json` files.
See https://v5.vite.dev/config/build-options.html#build-manifest

The manifest files are now generated to `public/vite/.vite/` rather than `public/vite/`.

The `vite_rails` project currently points the path to `public/vite/` only.
See:  https://github.com/sergii/vite_rails/blob/v1.0.12/lib/vite_rails/config.rb#L23-L30

This results in the following error

```
Vite Ruby can't find entrypoints/application.js in public/vite/manifest.json or public/vite/manifest-assets.json.
```

**Comment by skukx** [comment]
As a work around I've created an initializer and added the following code to override:
```ruby
ViteRails::Config.class_eval do
  def manifest_path
    build_output_dir.join('.vite', 'manifest.json')
  end

  def assets_manifest_path
    build_output_dir.join('.vite', 'manifest-assets.json')
  end
end
```

**Comment by ElMassimo** [comment]
The default manifest location in Vite 5 has been supported since #421.

It's the only location checked by default since #432, as seen [here](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/config.rb#L24).

> I have tried upgrading by running bundle update vite_ruby.

Did you?

**Comment by skukx** [comment]
Apologies, you are correct. I only upgraded `vite_rails` rather than `vite_ruby`
