### ISSUE TITLE
Is it possible do not use npx?

### ISSUE THREAD

**Issue by beqdot** [ElMassimo/vite_ruby#53]
In the docker with alpine linux and node it's not necessary to install npm, because yarn already used.
Here https://github.com/ElMassimo/vite_ruby/blob/b1f81358ee9c400e990b8fbddab779ff66c57f02/vite_ruby/lib/vite_ruby/cli/install.rb#L78 uses both packet managers.
I hope it could be one or other situation, but not both

**Comment by ElMassimo** [comment]
The advantage of using `npx` is that systems that have modern versions of Node typically include `npm` along with `npx`.

This command will add the dependencies using `yarn`, `npm`, or `pnpm`, depending on a lockfile in your project.

Would you clarify what's the problem you are running into?

**Comment by beqdot** [comment]
It's not the problem, I already add npm to Dockerfile, now it looks like `RUN apk add nodejs-current yarn npm` etc, before with webpacker it wasn't necessary to add npm. 
I can't say it's bad, but maybe better add this to documentation, that vite_ruby need both managers: npm and yarn.
