### ISSUE TITLE
[vite-plugin-ruby:assets-manifest] Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by nyrf** [ElMassimo/vite_ruby#55]
### Description 📖

When use image in stylesheet and run build, got error 

### Reproduction 🐞

just add css like this in `application.scss`

```
app/javascript/
├── entrypoints
│   ├── application.js
│   ├── application.scss
├── images
│   └── demo.png
└── stylesheets
    └── main.scss
```

```css
body {
  background: url("../images/demo.png")
}
```

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 1.2.3
vite_rails: 2.0.9
rails: 6.1.3.1
node: v15.4.0
npm: 7.0.15
yarn: 1.22.5
pnpm:
ruby: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin18]
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```
Building with Vite ⚡️
vite v2.1.5 building for production...
transforming...
✓ 68 modules transformed.
rendering chunks...
[vite-plugin-ruby:assets-manifest] Cannot read property 'substr' of undefined
error during build:
TypeError: Cannot read property 'substr' of undefined
    at withoutExtension (/Users/nyrf/Codes/rails/demo/vite_demo/node_modules/vite-plugin-ruby/dist/index.js:50:19)
    at /Users/nyrf/Codes/rails/demo/vite_demo/node_modules/vite-plugin-ruby/dist/index.js:123:19
    at Array.forEach (<anonymous>)
    at extractChunkStylesheets (/Users/nyrf/Codes/rails/demo/vite_demo/node_modules/vite-plugin-ruby/dist/index.js:122:69)
    at Object.generateBundle (/Users/nyrf/Codes/rails/demo/vite_demo/node_modules/vite-plugin-ruby/dist/index.js:149:7)
    at /Users/nyrf/Codes/rails/demo/vite_demo/node_modules/rollup/dist/shared/rollup.js:18863:25

Build with Vite failed! ❌
```
</details>

**Comment by ElMassimo** [comment]
Thanks for the report, must be a bug in 2.0.0 since every asset in the bundle is expected to have a name, which given the bug is not true for images.

I don't have my computer until next week—I'll investigate and create a patch.

**Comment by nyrf** [comment]
Thanks, i have tried to use previous version of `vite-plugin-ruby` and found another problem,  images in `app/javascript/images` folder can't be used by `vite_asset_path` in dev and production env.

```erb
<img src="<%= vite_asset_path 'images/hg.png' %>" />
```

stylesheet can use the hg.png as background

```css
body {
  background: url('../images/hg.png');
}
```

<img width="448" alt="WX20210417-114234@2x" src="https://user-images.githubusercontent.com/299532/115100848-258cba80-9f72-11eb-8856-079ebd822b02.png">


After build and run in production:

```
vite v2.1.5 building for production...
transforming...
✓ 70 modules transformed.
rendering chunks...
../../../public/vite/assets/hg.db495701.png            8.19kb
../../../public/vite/manifest-assets.json              0.00kb
../../../public/vite/manifest.json                     0.80kb
../../../public/vite/assets/application.23f17bc7.js    0.85kb / brotli: 0.44kb
../../../public/vite/assets/application.23f17bc7.js.map 4.05kb
../../../public/vite/assets/application.4b2ec947.css   4.26kb / brotli: 1.38kb
../../../public/vite/assets/index.1fe81b64.js          7.66kb / brotli: 2.23kb
../../../public/vite/assets/index.1fe81b64.js.map      25.24kb
../../../public/vite/assets/vendor.147ab07a.js         163.13kb / brotli: 40.78kb
../../../public/vite/assets/vendor.147ab07a.js.map     832.62kb
```

```log
ActionView::Template::Error (Vite Ruby can't find images/hg.png in public/vite/manifest.json or public/vite/manifest-assets.json.
```

`manifest.json`

```
{
  "application.js": {
    "file": "assets/application.23f17bc7.js",
    "src": "application.js",
    "isEntry": true,
    "imports": [
      "_vendor.147ab07a.js"
    ],
    "css": [
      "assets/application.4b2ec947.css"
    ],
    "assets": [
      "assets/hg.db495701.png"
    ]
  },
  "_vendor.147ab07a.js": {
    "file": "assets/vendor.147ab07a.js",
    "dynamicImports": [
      "../../../node_modules/@rails/actioncable/src/index.js"
    ]
  },
  "../../../node_modules/@rails/actioncable/src/index.js": {
    "file": "assets/index.1fe81b64.js",
    "src": "../../../node_modules/@rails/actioncable/src/index.js",
    "isDynamicEntry": true
  }
}
```

`manifest-assets.json` is empty

```
{}
```

**Comment by nyrf** [comment]
After move images folder into  entrypoints, it can work and the `hg.png`  generated twice after build 

```
../../../public/vite/assets/hg.db495701.png            8.19kb
../../../public/vite/assets/images/hg.db495701.png     8.19kb
```

```css
body {
  background: url('/images/hg.png');
}
```

```erb
<img src="<%= vite_asset_path 'images/hg.png' %>" />
```

**Comment by ElMassimo** [comment]
The `images` folder does not play a special role at the moment–moving it to entrypoints is correct if you want to use `vite_asset_path`.

Asset duplication seems like a bug in Rollup or Vite, I can look into it next week.

**Comment by nyrf** [comment]
@ElMassimo  Sorry, asset duplication seems caused by my mistake, it's not a bug.

**Comment by doabit** [comment]
I've created a PR for vite to solve the issue. https://github.com/vitejs/vite/pull/3050,  it also can solve custom manifest format problem.

**Comment by doabit** [comment]
Asset duplication because of put images in entrypoints folder, `vite-plugin-ruby` generated  a file and `vite` also generates file when you use the image in stylesheet. The right way is put images to `images` folder, if you want to use image in rails view, you should use global import  in `application.js`.

```js
import.meta.globEager('./images/**/*')
```

**Comment by tomocrafter** [comment]
I also came across this problem, Is there any workaround for this problem?
or Do I need to wait until this PR merges and releases?

**Comment by doabit** [comment]
> I also came across this problem, Is there any workaround for this problem?
> or Do I need to wait until this PR merges and releases?

I'm working on that, i'll submit a new PR to solve the two problem.

**Comment by ElMassimo** [comment]
Hi folks, adding the name to asset chunks would certainly simplify the internals of this library.

In the meantime (and to provide support to users in older Vite versions), I have fixed the build manifest error when referencing other assets, as well as the duplication problem in [`vite-plugin-ruby@2.0.1`](https://github.com/ElMassimo/vite_ruby/blob/f9c64b84544bd43ce5d5781d893e081ae8054042/vite-plugin-ruby/CHANGELOG.md#201-2021-04-21).

Please upgrade, and let me know how it goes.

**Comment by nyrf** [comment]
@ElMassimo It works, thanks.

**Comment by doabit** [comment]
> I also came across this problem, Is there any workaround for this problem?
> or Do I need to wait until this PR merges and releases?
ElMassimo  has done the great work. At beginning, my plan is to move vite `config.root` to `app/frontend` and puts images in `app/frontend/images`. I found  the newest version can work well with rails now. Thanks ElMassimo's great work.
