### ISSUE TITLE
DevProxy does not correctly rewrite url for *.min.css files

### ISSUE THREAD

**Issue by vladimirtemnikov** [ElMassimo/vite_ruby#70]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

At this moment `ViteRuby::DevServerProxy` tries to rewrite url for `*.min.css` files and then actually seeking them as `*.min` files on vite server.
I've tuned the regex to fix this problem.

**Comment by ElMassimo** [comment]
Hi Vladimir!

To provide some background on that regex, Rails does not have an equivalent to `extname: false` for `stylesheet_link_tag`, which means that serving `.scss` or `.less` files would require duplicating the entire method (maintenance nightmare across Rails versions).

I knew it would probably create problems out in the wild–thanks for taking the time to both report and __fix it__, really appreciate it!
