### ISSUE TITLE
Images only loading from within `entrypoints` directory

### ISSUE THREAD

**Issue by Jonic** [ElMassimo/vite_ruby#97]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

#### npm

* `"vite": "^2.4.1"`
* `"vite-plugin-environment": "^1.0.1"`
* `"vite-plugin-full-reload": "^0.2.2"`
* `"vite-plugin-ruby": "^2.0.4"`

#### Gems

* `vite_rails (2.0.12)`
* `vite_ruby (1.2.15)`

### Description 📖

I've been trying to migrate a Rails Webpacker app to vite-rails, but I'm encountering a problem that appears to be a bug (possibly a regression), according to the troubleshooting guide.

My `app/frontend` directory matches that in [the "entrypoints" section of the docs](https://vite-ruby.netlify.app/guide/development.html#entrypoints-%E2%A4%B5%EF%B8%8F).

I'm trying to use `vite_asset_path` to load an image kept in `app/frontend/images`, but is isn't loading, and it's not present in the `public/vite/assets` directory. If I move the image to inside `app/frontend/entrypoints`, then `vite_asset_path` is able to load it.

This is confusing because the troubleshooting guide specifically answers a question about images "[only load[ing] if placed on entrypoints](https://vite-ruby.netlify.app/guide/troubleshooting.html#images-only-load-if-placed-on-entrypoints)".

Adding to the confusion, one of the examples for `vite_asset_path` references `images/logo.svg`, without specifically mentioning where this `images` directory exists, which gives the impression that this is the example `images` directory mentioned in the "entrypoints" section.

Is this actually a bug, and loading from `app/frontend/images` should be possible? Or is it only the case that `vite_asset_path` will only be able to see anything kept in `app/frontend/entrypoints`?

Whatever the case, I think the Rails tag helper docs and troubleshooting guide are confusing matters a little, and I would have also expected a warning or error upon passing a file into `vite_asset_path` that isn't found in the manifest.

I've checked the example Rails app, which does keep its images in `app/frontend/entrypoints/images`, so after all this I can't figure out if I've read the docs incorrectly, or if something's missing from the docs, or if the docs are incorrect, or if all of this is actually a bug!

Sorry for writing such a huge issue. Any help would be appreciated!

**Comment by ElMassimo** [comment]
Hi Jonic!

The Troubleshooting guide is indeed misleading in this scenario, I will update it accordingly.

To answer your question, all tag helpers including `vite_asset_path` can only reference files in the `entrypoints` directory.

If you are only referencing images from any JS or CSS processed by Vite, you would be able to import them without placing them under `entrypoints`.

**Comment by ElMassimo** [comment]
Updated the docs, removed the reference to an unrelated older issue in Vite, and clarified where the assets are located in the Rails `vite_asset_path` example.

Thanks!

**Comment by Jonic** [comment]
@ElMassimo Thanks for the clarification - it's much clearer now! I was hoping to use Github's [ViewComponent](https://viewcomponent.org/) gem, keeping each component's assets with the Ruby class and `erb` template, for example:

```
app/components/header_component
  ./header.rb
  ./header.erb
  ./header.scss
  ./header.js
  ./images/logo.svg
```

I understand that I'd have to import the Sass and JS from an entrypoint, and that these files can in turn load images, but would I be unable to reference the images with `vite_asset_path` since they're not in the `entrypoints` directory? I'm still trying to figure out if Vite Ruby could be an easy-ish drop-in replacement for our current setup, or if it would involve significant reshuffling and a massive PR to make it all happen. Apologies if I'm being dense!

**Comment by ElMassimo** [comment]
@Jonic If you are referring to [Sidecar Assets](https://viewcomponent.org/guide/sidecar_assets.html), it should be possible to do something similar in Vite Ruby.

Instead of `require.context` you would use a [`globEager` import](https://vitejs.dev/guide/features.html#glob-import).

[Here's an example](https://github.com/ElMassimo/jumpstart-vite/blob/master/app/javascript/controllers/index.js) using `globEager` to register all Stimulus controllers.

If you are referencing individual assets from Rails views or partials directly, then it's not going to be a drop-in replacement, but if you are combining the components in a single "pack" it should be easier.

> would I be unable to reference the images with vite_asset_path since they're not in the entrypoints directory?

No. When using Vite.js you would ideally `import` the images in the relevant component and use their source in the component itself.
