### ISSUE TITLE
Importing CSS modules fails

### ISSUE THREAD

**Issue by theodoretliu** [ElMassimo/vite_ruby#98]
Hi, really love this project, and super excited to continue testing it out :) 

In one of my Javascript files, I'm attempting to import CSS Modules via 
```
import styles from './styles.module.css'
```
but this is generating errors like the following in my Chrome console
```
GET http://localhost:3002/vite-dev/@fs/app/javascript/src/components/LeftNav/styles.module.css net::ERR_ABORTED 404 (Not Found)
```
am I missing a step here?

**Comment by ElMassimo** [comment]
Hi Theodore! Thanks for reporting.

It seems to be related to the dev server proxy, where the `.css` extension is being removed before forwarding the request to the Vite dev server.

Releasing a new version with the patch soon.

**Comment by ElMassimo** [comment]
@theodoretliu Upgrading `vite_ruby` to `1.2.17` should allow CSS Modules requests to be served correctly in development. Thanks again for the report!
